### ISSUE TITLE
Area of symbols specified in "real" pixels

### ISSUE THREAD

**Issue by hadley** [vega/vega-scenegraph#10]
Instead of virtual pixels - this makes the size of symbols different between retina and non-retina displays (relative to the rest of the plot). This is also a problem for `fontSize` and the text mark.

**Comment by jheer** [comment]
Closing out this issue as it applies to an earlier version of vega-scenegraph and should be handled by the [resizing logic applied in the case of retina displays](https://github.com/vega/vega-scenegraph/blob/master/src/util/canvas/resize.js#L21). Feel free to re-open should any issues persist.
