### ISSUE TITLE
Mouse events not working correctly after scrolling

### ISSUE THREAD

**Issue by seyfert** [vega/vega-scenegraph#11]
Hi,
I just re-discovered Vega with the 2.0 release today.  It's looking great and can't wait to start using it in my projects!

However, I noticed an issue when attempting to interact with a chart on a page that has been scrolled.  The x/y coordinates being calculated are not correct.

The bug seems to be in the CanvasHandler pickEvent function.  The x/y coordinates are being set based on the viewport (clientX/clientY) instead of the page.

See http://codepen.io/seyfert/pen/GJGxLb?editors=101

**Comment by jheer** [comment]
Thanks! Turns out the use of clientX/clientY coordinates is fine, as they are compared against the output of getBoundingClientRect, which uses the same coordinate system. However, the bounding rect was being cached incorrectly, leading to the error. This was fixed in e39d8ad.
