### ISSUE TITLE
Default transparent fill on group marks?

### ISSUE THREAD

**Issue by arvind** [vega/vega-scenegraph#16]
Issues like vega/vega#380 strike me as an unnecessary gotcha. Is there any harm in setting a transparent fill to group marks by default?

**Comment by jheer** [comment]
I agree that this can lead to annoying and unintuitive cases for users. However, is they captured events by default, layered groups (e.g., multi-layer plots, stacked areas, line charts, etc) could block UI events from reaching the desired marks. We don't want groups to capture the input events in these cases. At this point I don't see a clean solution that is better than the current setup. Note that the current setup also matches SVG behavior (e.g., null-fills do not capture events, transparent-fills do).

Thoughts?

**Comment by jheer** [comment]
This was further discussed offline. Closing issue as no changes are to be made at this time.
