### ISSUE TITLE
More granular bounds bookkeeping/methods

### ISSUE THREAD

**Issue by arvind** [vega/vega-scenegraph#20]
I pushed a fix for vega/vega#429, but I'm not satisfied that it's the best way to address bugs with bound calculations. 

Currently, the responsibility is on Vega to do the bookkeeping of whether mark or item bounds need to be calculated. And the logic is overly crude due to the APIs provided by vega-scenegraph -- only mark or itemBounds are exposed, with the former calling the later on _all_ items, an expensive operation. 

Instead, ideally, Vega would call item bounds for all the items it sees. vega-scenegraph would do the necessary bookkeeping to figure out whether an item that lay on the edge of the mark bounds has changed, and if so update the mark bounds.

**Comment by jheer** [comment]
Superseded by vega/vega#454.
