### ISSUE TITLE
datalib hardcoded to window.dl

### ISSUE THREAD

**Issue by arvind** [vega/vega-scenegraph#3]
Datalib is hardcoded to `window.dl` in several files:
*  `ImageLoader`
* `SVGRenderer` and `SVGHandler`

This is `undefined` when I include and browserify `vega-scenegraph` + `datalib` within vega2.

**Comment by jheer** [comment]
This is fixed. Now `ImageLoader` has the only `datalib` dependency, and pulls the `load` sub-module only. I updated the dirtyChecking branch over on Vega 2 to take advantage of this, and everything bundles appropriately.

**Comment by arvind** [comment]
Woo hoo, thanks for this! Was not looking forward to figuring it out :)
