### ISSUE TITLE
SVG renderer does not DataJoin for modified dataset

### ISSUE THREAD

**Issue by arvind** [vega/vega-scenegraph#33]
With [this example](https://gist.github.com/arvind/0cb8a8e800b49489a0ec6cbe332efa99), and again apologies I was not able to reproduce the issue with a more minimal one, the following behaviour is expected:

1. Brush within a cell of the SPLOM. 
2. Observe a grey rect corresponding to the brushed extents stored in the signal. 
3. Observe a red rect corresponding to the same extents stored in a backing dataset. 

With the Canvas renderer, this is indeed what I observe. However, the red rect does not appear with the SVG renderer. The scenegraph is correctly populated -- I observe an `Item` with the correct properties set but the `_svg` property is `null`.

**Comment by jheer** [comment]
This problem appears to go away after I fix L106:
`"update": "modify('brush_selection', brush_tuple, brush_tuple)"`

Again, this line is adding and removing the same identical tuple, which doesn't make a lot of sense. Closing for now. Please comment/reopen if you find a well-isolated scenegraph bug. In this case, I suspect the added tuple is being marked as "exit", which is ignored by the canvas renderer but used by the SVG renderer to cull the DOM.

**Comment by arvind** [comment]
Where's the facepalm emoji when you need it!
