### ISSUE TITLE
Allow anti-aliasing to be turned off on a per-mark basis

### ISSUE THREAD

**Issue by besquared** [vega/vega-scenegraph#36]
By default paths in SVG and Canvas are smoothed which creates soft/smoothed edges on everything. There are times when it creates a better presentation to turn off the anti-aliasing on a per-mark basis.

For SVG that means adding a style to the mark element such as

```
style="shape-rendering:crispEdges"
```

For canvas the best way to do this is probably using a sub-pixel translation as described here:

http://www.mobtowers.com/html5-canvas-crisp-lines-every-time/

You can store a variable that translates and then translates back when necessary. I'll admit I'm not too familiar with the scenegraph so don't know how possible this particular approach it.

**Comment by besquared** [comment]
Turns out you can mostly do this yourself in various ways:

For the mark in question you can add an offset of 0.5 to x, xc, y, or yc, to get the corresponding sharpness along that dimension. This works in both canvas and SVG at least on chrome in OSX. Will have to do more testing in other environments.

**Comment by jheer** [comment]
Thanks for raising the issue. As you note, you can use sub-pixel offsets directly in a Vega spec and this passed through to the scenegraph. Alternatively, for SVG you are free to include an external CSS file to modify the rendering parameters. A related option is the use of `round: true` on scale mappings to force coordinates to the pixel grid. I'm closing the issue for now.
