### ISSUE TITLE
Support for line joins besides miter?

### ISSUE THREAD

**Issue by mbostock** [vega/vega-scenegraph#38]
Per [styles.js](https://github.com/vega/vega-scenegraph/blob/master/src/util/svg/styles.js), it seems there’s not currently a way to use non-miter line join ([stroke-linejoin](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linejoin), [lineJoin](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineJoin)). And since it’s also not possible to control the miter limit ([stroke-miterlimit](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-miterlimit), [miterLimit](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/miterLimit)) for the default join, dense data can be a bit spiky:

![image](https://cloud.githubusercontent.com/assets/230541/25056508/35517f4a-211e-11e7-9c21-fcf5592267ea.png)

You can workaround this issue by using a different line interpolator (such as cardinal or step), but if it’s easy to implement, it’d be nice to be able to use round line joins, too.

**Comment by jheer** [comment]
Thanks! Added support for `strokeJoin` and `strokeMiterLimit` encoding properties in 7f0b1ed, now released as part of vega-scenegraph version 2.0.0-beta.26.
