### ISSUE TITLE
Support text marks with mixed styling for a single text item.

### ISSUE THREAD

**Issue by GCheung55** [vega/vega-scenegraph#50]
SVG has `tspan` nodes that provides mixed styling within a `text` node. This would be useful for styling mixed text.

**Comment by jheer** [comment]
Right now vega scenegraph items have a flat property structure, with properties for `text`, `font`, `fontSize`, etc. It is not clear if/how this should be redesigned or altered to enable specification of mixed styling for text.

Second, in terms of rendering there is a question of how to support Canvas rendering. Similar to HTML, SVG can support some level of text layout. However, in Canvas it seems that mixed styling would also require custom text flow layout to correctly position each sub-span.

As a result, this is unlikely to be added to in the near future. However, we are happy to consider concrete proposals!

**Comment by jheer** [comment]
Closing out issue as we are archiving this repository.
