### ISSUE TITLE
Axes should (probably?) draw over marks

### ISSUE THREAD

**Issue by ericsoco** [vega/vega-scenegraph#56]
Seems to me that axes, as annotations, should be drawn over marks, not under them. Currently this is not the case:

<img width="174" alt="screen shot 2017-10-26 at 11 14 59 am" src="https://user-images.githubusercontent.com/1127259/32069943-98894d44-ba3f-11e7-95b2-5f1659f4734b.png">

<img width="330" alt="screen shot 2017-10-26 at 11 20 49 am" src="https://user-images.githubusercontent.com/1127259/32070020-c9f1fc0a-ba3f-11e7-979e-9abaf0bc6548.png">

I'm guessing scenegraph is the right place for this issue, but not sure.

**Comment by domoritz** [comment]
You can change the zindex of marks. Vega-Lite puts axes in the foreground by default: https://vega.github.io/editor/#/examples/vega-lite/bar.

**Comment by jheer** [comment]
What @domoritz said. There is not one correct placement for axes. Sometimes you want the axes or gridlines behind your marks, other times you want them on top. Documentation of the axis `zindex` property is at https://vega.github.io/vega/docs/axes/. Typically you just set `"zindex": 1` in your axis specification.

At the scenegraph level the zindex property is used to sort sibling items (it is not a globally applied index) and determine their draw order. For axes, this happens at the group level (e.g., to draw the group containing the axis over the groups containing marks).

**Comment by ericsoco** [comment]
Great, this works well for my needs and keeps things flexible for others'. 🙏
