### ISSUE TITLE
Name value as CSS class name for SVG group

### ISSUE THREAD

**Issue by arvind** [vega/vega-scenegraph#6]
> As of Vega v1.4.0, the SVG renderer adds the _unaltered_ name value as CSS class names on the enclosing SVG group (`g`) element for mark instances.

I don't think this is supported, anymore. Did we want to reintroduce it?

**Comment by jheer** [comment]
This is still supported, but with a slight departure from 1.x. See the `cssClass` function in [util/dom.js](https://github.com/vega/vega-scenegraph/blob/master/src/util/dom.js#L51). We now look for the class name under `mark.name` (where `mark` is the intermediate mark scenegraph node).

The previous method was to look at `def.name`, however, the `def` object is internal to Vega proper and not part of the (now modularized) scenegraph definition. So I think the right fix here is to make sure the Vega build stage adds the name property (if defined) to intermediate mark nodes in the scenegraph.

**Comment by arvind** [comment]
Ah right, of course! Fixed with uwdata/vega@ecc49b1
