### ISSUE TITLE
Tooltip handler returns inconsistent events based on the renderer. 

### ISSUE THREAD

**Issue by domoritz** [vega/vega-scenegraph#60]
I get different tooltip events in Canvas and SVG. In Canvas I get `'mouseout'` when I enter a mark and `undefined` when I exit. In SVG, I get `'mouseover'` and `'mouseout'`.

**Comment by jheer** [comment]
I assume you are referring to `vegaType`? It turns out the CanvasHandler does not set the current value until _after_ the tooltip handler is invoked. I can change that to ensure it is set prior to invoking _any_ handlers.

**Comment by domoritz** [comment]
Yes, I am talking about `vegaType`.

Vega-Tooltip currently only works either in Cavas or SVG because events are inconsistent. Should I wait for a fix (+release) in Vega or is there some workaround?

**Comment by jheer** [comment]
I can push a patch release with this fix. Hopefully by EOD (4/22).

**Comment by domoritz** [comment]
Thank you. I will wait then and not patch Vega tooltip.

**Comment by jheer** [comment]
v3.3.1 has been released. A note for when you finalize Vega tooltip: if looking at the `vegaType` property, I recommend checking whether or not it is `"mouseout"` to see if the tooltip should be hidden. Currently the `vegaType` upon initial tooltip show will be `"mouseover"`, but that will change to `"mousemove"` in a subsequent Vega version.

That said, I don't think you should rely on the `vegaType` at all! The tooltip handler should always receive a `null` _value_ argument when tooltips should be hidden. See https://vega.github.io/vega/docs/api/view/#view_tooltip
