### ISSUE TITLE
On click handler 

### ISSUE THREAD

**Issue by ted-dunstone** [vega/vega-scenegraph#65]
Currently, when an href is specified for an onclick event, there is no obvious way of specifying a window target (in other words to make a click open a window rather than navigate away from the current page) - the suggestion is that a config could be given to allow an alternate **href** target.

Relevant function is:

Handler.js line 423: 
> prototype.handleHref = function(event, item, href) 

Ideally, it would also be great to be able to overload this function in local javascript after loading the library to allow custom actions on click. Would this currently be possible?

**Comment by domoritz** [comment]
You can set the target in the loader. See https://github.com/vega/vega/issues/1171

**Comment by ted-dunstone** [comment]
Awesome, thanks for your quick reply.

*Ted Dunstone*
Managing  Director
Biometix Pty Ltd

E: ted@biometix.com
T: 0419 990968
W: www.biometix.com
A: 8/65 Canberra Ave, Manuka, ACT, 2603

*This message (including any attachments) is intended solely for
the addressee named and may contain confidential information. If you
are not the intended recipient, please delete it and notify the sender. The
whole or parts of this e-mail (and attachments) may be subject to copyright
of Biometix or third parties. You should only re-transmit, distribute or
use the material for commercial purposes if you are authorised to do so.*
