### ISSUE TITLE
Layering of multiple gridlines

### ISSUE THREAD

**Issue by arvind** [vega/vega-scenegraph#7]
From vega/vega#269:

![pole](https://cloud.githubusercontent.com/assets/111269/7551137/37f57f30-f632-11e4-9ebc-984ee276fce0.png)

This is occurring because the group mark of one axes follows another, and ergo the gridlines of the latter wipe out the axis of the former.

**Comment by kanitw** [comment]
FYI, for now in https://github.com/uwdata/vega-lite we add alpha to the gridline as a workaround for this issue.

**Comment by jheer** [comment]
Technically this is not a scenegraph bug and so I'm closing the issue. Each set of axis components resides in a separate group, with subsequent groups painted over each other. So in that sense the scene is being rendered correctly.

Here are a couple possible responses:

1. Change the vega defaults to use translucent gridlines as suggested by @kanitw.
2. Change vega's axis logic to generate an alternate scenegraph structure.
3. Change the scenegraph to support z-ordering.

Option 1 is the most expedient for now, and option 2 something to consider in the future. Option 3 should be a separate feature request issue; I think we should avoid it for now, as it would require significant revision to the rendering infrastructure.
